package com.orionsolwings.osbiz.common.enums;

public enum ApplicationModules {
    BUSINESS_PARTNER,
    INVOICE,
    TRANSACTION,
    CATALOGUE,
    PURCHASE_ORDER,
    PURCHASE_RETURN,
    PAYABLES,
    INVENTORY,
    INDENT,
    PAYMENTS,
    AMENTS,
    EXPENSE,
    EMPLOYEES,
    TIMESHEETS,
    SUBMISSION,
    REPORT,
    BUSINESS_SETUP,
    GENERAL_LEDGER,
    NUMBER_RANGE,
    EMAIL_TEMPLATE,
    INVOICE_TEMPLATE,
    PAYMENTS_INTEGRATION
}
