package com.orionsolwings.osbiz.common.enums;

public enum ModuleNumberRange {
	BUSINESS_PARTNER, INVOICE, TRANSACTION, CATALOGUE, PURCHASE_ORDER, PURCHASE_RETURN, INVENTORY, INDENT, PAYMENT,
	MEMO, EMPLOYEE, PAYSLIP, GLACCOUNT
}
